server:
  port: 8081

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/palago
    username: palago
    password: palago00
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: oosoojh31@gmail.com
    password: sqtupkwcndqbwpis
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  paths-to-match: /**
  swagger-ui:
    path: /
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    disable-swagger-default-url: true
  api-docs:
    groups:
      enabled: true

jasypt:
  encryptor:
    bean: propertyEncryptor
  secret-key: ${JASYPT_PASSWORD}

